name = "burme-ai"
main = "src/index.js"
compatibility_date = "2025-07-30"

[vars]
# Remove the actual API key from this file
# GEMINI_API_KEY will be set via secrets

[build]
command = "npm run build"

[dev]
port = 8787
